// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v3.19.4
// source: proto/PostAvatar.proto

package PostAvatar

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostAvatarRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// binary photo atream
	Avatar   []byte `protobuf:"bytes,2,opt,name=Avatar,proto3" json:"Avatar,omitempty"`
	FileSize int64  `protobuf:"varint,3,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	FileExt  string `protobuf:"bytes,4,opt,name=file_ext,json=fileExt,proto3" json:"file_ext,omitempty"`
}

func (x *PostAvatarRequest) Reset() {
	*x = PostAvatarRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_PostAvatar_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostAvatarRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAvatarRequest) ProtoMessage() {}

func (x *PostAvatarRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PostAvatar_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAvatarRequest.ProtoReflect.Descriptor instead.
func (*PostAvatarRequest) Descriptor() ([]byte, []int) {
	return file_proto_PostAvatar_proto_rawDescGZIP(), []int{0}
}

func (x *PostAvatarRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostAvatarRequest) GetAvatar() []byte {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *PostAvatarRequest) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *PostAvatarRequest) GetFileExt() string {
	if x != nil {
		return x.FileExt
	}
	return ""
}

type PostAvatarResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno  string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	// partial url for avatar
	AvatarUrl string `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
}

func (x *PostAvatarResponse) Reset() {
	*x = PostAvatarResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_PostAvatar_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostAvatarResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostAvatarResponse) ProtoMessage() {}

func (x *PostAvatarResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PostAvatar_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostAvatarResponse.ProtoReflect.Descriptor instead.
func (*PostAvatarResponse) Descriptor() ([]byte, []int) {
	return file_proto_PostAvatar_proto_rawDescGZIP(), []int{1}
}

func (x *PostAvatarResponse) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *PostAvatarResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *PostAvatarResponse) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

var File_proto_PostAvatar_proto protoreflect.FileDescriptor

var file_proto_PostAvatar_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76,
	0x61, 0x74, 0x61, 0x72, 0x22, 0x82, 0x01, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x66, 0x69, 0x6c, 0x65, 0x45, 0x78, 0x74, 0x22, 0x62, 0x0a, 0x12, 0x50, 0x6f, 0x73,
	0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x55, 0x72, 0x6c, 0x32, 0x5b, 0x0a,
	0x0a, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x4d, 0x0a, 0x0a, 0x50,
	0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1d, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x41,
	0x76, 0x61, 0x74, 0x61, 0x72, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a, 0x12, 0x2e, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x50, 0x6f, 0x73, 0x74, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_PostAvatar_proto_rawDescOnce sync.Once
	file_proto_PostAvatar_proto_rawDescData = file_proto_PostAvatar_proto_rawDesc
)

func file_proto_PostAvatar_proto_rawDescGZIP() []byte {
	file_proto_PostAvatar_proto_rawDescOnce.Do(func() {
		file_proto_PostAvatar_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_PostAvatar_proto_rawDescData)
	})
	return file_proto_PostAvatar_proto_rawDescData
}

var file_proto_PostAvatar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_PostAvatar_proto_goTypes = []interface{}{
	(*PostAvatarRequest)(nil),  // 0: PostAvatar.PostAvatarRequest
	(*PostAvatarResponse)(nil), // 1: PostAvatar.PostAvatarResponse
}
var file_proto_PostAvatar_proto_depIdxs = []int32{
	0, // 0: PostAvatar.PostAvatar.PostAvatar:input_type -> PostAvatar.PostAvatarRequest
	1, // 1: PostAvatar.PostAvatar.PostAvatar:output_type -> PostAvatar.PostAvatarResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_PostAvatar_proto_init() }
func file_proto_PostAvatar_proto_init() {
	if File_proto_PostAvatar_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_PostAvatar_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostAvatarRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_PostAvatar_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostAvatarResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_PostAvatar_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_PostAvatar_proto_goTypes,
		DependencyIndexes: file_proto_PostAvatar_proto_depIdxs,
		MessageInfos:      file_proto_PostAvatar_proto_msgTypes,
	}.Build()
	File_proto_PostAvatar_proto = out.File
	file_proto_PostAvatar_proto_rawDesc = nil
	file_proto_PostAvatar_proto_goTypes = nil
	file_proto_PostAvatar_proto_depIdxs = nil
}
