// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetImageCd.proto

package GetImageCd

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetImageCd service

func NewGetImageCdEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetImageCd service

type GetImageCdService interface {
	GetImageCd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type getImageCdService struct {
	c    client.Client
	name string
}

func NewGetImageCdService(name string, c client.Client) GetImageCdService {
	return &getImageCdService{
		c:    c,
		name: name,
	}
}

func (c *getImageCdService) GetImageCd(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "GetImageCd.GetImageCd", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetImageCd service

type GetImageCdHandler interface {
	GetImageCd(context.Context, *Request, *Response) error
}

func RegisterGetImageCdHandler(s server.Server, hdlr GetImageCdHandler, opts ...server.HandlerOption) error {
	type getImageCd interface {
		GetImageCd(ctx context.Context, in *Request, out *Response) error
	}
	type GetImageCd struct {
		getImageCd
	}
	h := &getImageCdHandler{hdlr}
	return s.Handle(s.NewHandler(&GetImageCd{h}, opts...))
}

type getImageCdHandler struct {
	GetImageCdHandler
}

func (h *getImageCdHandler) GetImageCd(ctx context.Context, in *Request, out *Response) error {
	return h.GetImageCdHandler.GetImageCd(ctx, in, out)
}
