// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/GetUserHouses.proto

package GetUserHouses

import (
	fmt "fmt"
	proto "google.golang.org/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "go-micro.dev/v4/api"
	client "go-micro.dev/v4/client"
	server "go-micro.dev/v4/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for GetUserHouses service

func NewGetUserHousesEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for GetUserHouses service

type GetUserHousesService interface {
	GetUserHouses(ctx context.Context, in *GetUserHousesRequest, opts ...client.CallOption) (*GetUserHousesResponse, error)
}

type getUserHousesService struct {
	c    client.Client
	name string
}

func NewGetUserHousesService(name string, c client.Client) GetUserHousesService {
	return &getUserHousesService{
		c:    c,
		name: name,
	}
}

func (c *getUserHousesService) GetUserHouses(ctx context.Context, in *GetUserHousesRequest, opts ...client.CallOption) (*GetUserHousesResponse, error) {
	req := c.c.NewRequest(c.name, "GetUserHouses.GetUserHouses", in)
	out := new(GetUserHousesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GetUserHouses service

type GetUserHousesHandler interface {
	GetUserHouses(context.Context, *GetUserHousesRequest, *GetUserHousesResponse) error
}

func RegisterGetUserHousesHandler(s server.Server, hdlr GetUserHousesHandler, opts ...server.HandlerOption) error {
	type getUserHouses interface {
		GetUserHouses(ctx context.Context, in *GetUserHousesRequest, out *GetUserHousesResponse) error
	}
	type GetUserHouses struct {
		getUserHouses
	}
	h := &getUserHousesHandler{hdlr}
	return s.Handle(s.NewHandler(&GetUserHouses{h}, opts...))
}

type getUserHousesHandler struct {
	GetUserHousesHandler
}

func (h *getUserHousesHandler) GetUserHouses(ctx context.Context, in *GetUserHousesRequest, out *GetUserHousesResponse) error {
	return h.GetUserHousesHandler.GetUserHouses(ctx, in, out)
}
