// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: proto/PostHouses.proto

package PostHouses

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostHousesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Houses    []byte `protobuf:"bytes,2,opt,name=houses,proto3" json:"houses,omitempty"`
}

func (x *PostHousesRequest) Reset() {
	*x = PostHousesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_PostHouses_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostHousesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHousesRequest) ProtoMessage() {}

func (x *PostHousesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PostHouses_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHousesRequest.ProtoReflect.Descriptor instead.
func (*PostHousesRequest) Descriptor() ([]byte, []int) {
	return file_proto_PostHouses_proto_rawDescGZIP(), []int{0}
}

func (x *PostHousesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PostHousesRequest) GetHouses() []byte {
	if x != nil {
		return x.Houses
	}
	return nil
}

type PostHousesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Errno   string `protobuf:"bytes,1,opt,name=errno,proto3" json:"errno,omitempty"`
	ErrMsg  string `protobuf:"bytes,2,opt,name=err_msg,json=errMsg,proto3" json:"err_msg,omitempty"`
	HouseId string `protobuf:"bytes,3,opt,name=house_id,json=houseId,proto3" json:"house_id,omitempty"`
}

func (x *PostHousesResponse) Reset() {
	*x = PostHousesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_PostHouses_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostHousesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostHousesResponse) ProtoMessage() {}

func (x *PostHousesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_PostHouses_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostHousesResponse.ProtoReflect.Descriptor instead.
func (*PostHousesResponse) Descriptor() ([]byte, []int) {
	return file_proto_PostHouses_proto_rawDescGZIP(), []int{1}
}

func (x *PostHousesResponse) GetErrno() string {
	if x != nil {
		return x.Errno
	}
	return ""
}

func (x *PostHousesResponse) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

func (x *PostHousesResponse) GetHouseId() string {
	if x != nil {
		return x.HouseId
	}
	return ""
}

var File_proto_PostHouses_proto protoreflect.FileDescriptor

var file_proto_PostHouses_proto_rawDesc = []byte{
	0x0a, 0x16, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x73, 0x22, 0x4a, 0x0a, 0x11, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x68, 0x6f, 0x75, 0x73,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x73,
	0x22, 0x5e, 0x0a, 0x12, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6e, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x65, 0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65,
	0x72, 0x72, 0x4d, 0x73, 0x67, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x75, 0x73, 0x65, 0x49, 0x64,
	0x32, 0x5b, 0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x12, 0x4d,
	0x0a, 0x0a, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x50,
	0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f,
	0x75, 0x73, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x50, 0x6f,
	0x73, 0x74, 0x48, 0x6f, 0x75, 0x73, 0x65, 0x73, 0x2e, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x14, 0x5a,
	0x12, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x3b, 0x50, 0x6f, 0x73, 0x74, 0x48, 0x6f, 0x75,
	0x73, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_PostHouses_proto_rawDescOnce sync.Once
	file_proto_PostHouses_proto_rawDescData = file_proto_PostHouses_proto_rawDesc
)

func file_proto_PostHouses_proto_rawDescGZIP() []byte {
	file_proto_PostHouses_proto_rawDescOnce.Do(func() {
		file_proto_PostHouses_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_PostHouses_proto_rawDescData)
	})
	return file_proto_PostHouses_proto_rawDescData
}

var file_proto_PostHouses_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_PostHouses_proto_goTypes = []interface{}{
	(*PostHousesRequest)(nil),  // 0: PostHouses.PostHousesRequest
	(*PostHousesResponse)(nil), // 1: PostHouses.PostHousesResponse
}
var file_proto_PostHouses_proto_depIdxs = []int32{
	0, // 0: PostHouses.PostHouses.PostHouses:input_type -> PostHouses.PostHousesRequest
	1, // 1: PostHouses.PostHouses.PostHouses:output_type -> PostHouses.PostHousesResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_PostHouses_proto_init() }
func file_proto_PostHouses_proto_init() {
	if File_proto_PostHouses_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_PostHouses_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostHousesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_PostHouses_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostHousesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_PostHouses_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_PostHouses_proto_goTypes,
		DependencyIndexes: file_proto_PostHouses_proto_depIdxs,
		MessageInfos:      file_proto_PostHouses_proto_msgTypes,
	}.Build()
	File_proto_PostHouses_proto = out.File
	file_proto_PostHouses_proto_rawDesc = nil
	file_proto_PostHouses_proto_goTypes = nil
	file_proto_PostHouses_proto_depIdxs = nil
}
